/**
 * Integration Tests for Export Pipeline
 * Tests PNG, SVG, PDF, and TikZ export functionality with various options
 *
 * @module tests/integration/exportPipeline
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { PNGExporter } from '../../src/services/export/PNGExporter';
import { SVGExporter } from '../../src/services/export/SVGExporter';
import { PDFExporter } from '../../src/services/export/PDFExporter';
import {
  createMockFabricCanvas,
  waitForStateUpdate,
} from '../setup';
import type { DPI } from '../../src/services/export/types';

// ============================================================================
// Mock TikZ Exporter (not yet implemented in source)
// ============================================================================

/**
 * Mock TikZ Exporter for testing
 */
class TikZExporter {
  readonly format = 'tikz' as const;

  getDefaultOptions() {
    return {
      standalone: false,
      includePreamble: true,
      scale: 1,
      unit: 'cm' as const,
      includeComments: true,
      filename: 'illustration',
    };
  }

  validateOptions(options?: Partial<TikZExportOptions>): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (options?.scale !== undefined && options.scale <= 0) {
      errors.push('Scale must be positive');
    }

    if (options?.unit && !['cm', 'mm', 'pt', 'in'].includes(options.unit)) {
      errors.push('Invalid unit');
    }

    return { valid: errors.length === 0, errors };
  }

  async export(
    canvas: ReturnType<typeof createMockFabricCanvas>,
    options?: Partial<TikZExportOptions>,
    onProgress?: (progress: number, message?: string) => void
  ): Promise<{ blob: Blob; filename: string; mimeType: string; size: number }> {
    const opts = { ...this.getDefaultOptions(), ...options };

    onProgress?.(0, 'Analyzing canvas objects...');

    const validation = this.validateOptions(opts);
    if (!validation.valid) {
      throw new Error(`Invalid options: ${validation.errors.join(', ')}`);
    }

    onProgress?.(20, 'Converting to TikZ coordinates...');

    // Generate TikZ code
    let tikzCode = '';

    if (opts.standalone) {
      tikzCode += '\\documentclass{standalone}\n';
      tikzCode += '\\usepackage{tikz}\n';
      tikzCode += '\\begin{document}\n';
    }

    if (opts.includePreamble && !opts.standalone) {
      tikzCode += '% Include in preamble: \\usepackage{tikz}\n';
    }

    onProgress?.(40, 'Generating TikZ code...');

    tikzCode += '\\begin{tikzpicture}';
    if (opts.scale !== 1) {
      tikzCode += `[scale=${opts.scale}]`;
    }
    tikzCode += '\n';

    if (opts.includeComments) {
      tikzCode += '  % Generated by FINNISH Export Pipeline\n';
    }

    // Process objects
    const objects = canvas.getObjects();
    for (const obj of objects) {
      tikzCode += this.objectToTikZ(obj, opts);
    }

    tikzCode += '\\end{tikzpicture}\n';

    if (opts.standalone) {
      tikzCode += '\\end{document}\n';
    }

    onProgress?.(80, 'Creating output file...');

    const blob = new Blob([tikzCode], { type: 'text/x-tex' });
    const filename = `${opts.filename || 'illustration'}.tex`;

    onProgress?.(100, 'Export complete');

    return {
      blob,
      filename,
      mimeType: 'text/x-tex',
      size: blob.size,
    };
  }

  private objectToTikZ(
    obj: { type: string; left?: number; top?: number; width?: number; height?: number; radius?: number; fill?: string; stroke?: string },
    opts: { unit: string; includeComments?: boolean }
  ): string {
    const { unit, includeComments } = opts;
    let code = '';

    const x = (obj.left ?? 0) / 100;
    const y = -(obj.top ?? 0) / 100; // Flip Y axis for TikZ

    switch (obj.type) {
      case 'rect': {
        const w = (obj.width ?? 100) / 100;
        const h = (obj.height ?? 100) / 100;
        if (includeComments) {
          code += `  % Rectangle\n`;
        }
        const fillOpt = obj.fill ? `fill=${this.colorToTikZ(obj.fill as string)}` : '';
        const drawOpt = obj.stroke ? `draw=${this.colorToTikZ(obj.stroke as string)}` : 'draw';
        code += `  \\${fillOpt ? 'filldraw' : 'draw'}[${[fillOpt, drawOpt].filter(Boolean).join(', ')}] (${x}${unit}, ${y}${unit}) rectangle (${x + w}${unit}, ${y - h}${unit});\n`;
        break;
      }
      case 'circle': {
        const r = (obj.radius ?? 50) / 100;
        if (includeComments) {
          code += `  % Circle\n`;
        }
        code += `  \\draw (${x}${unit}, ${y}${unit}) circle (${r}${unit});\n`;
        break;
      }
      case 'line': {
        if (includeComments) {
          code += `  % Line\n`;
        }
        code += `  \\draw (${x}${unit}, ${y}${unit}) -- (${x + 1}${unit}, ${y}${unit});\n`;
        break;
      }
      default:
        if (includeComments) {
          code += `  % Unsupported object type: ${obj.type}\n`;
        }
    }

    return code;
  }

  private colorToTikZ(color: string): string {
    if (color.startsWith('#')) {
      return `{rgb,255:red,${parseInt(color.slice(1, 3), 16)};green,${parseInt(color.slice(3, 5), 16)};blue,${parseInt(color.slice(5, 7), 16)}}`;
    }
    return color;
  }

  async exportAsString(
    canvas: ReturnType<typeof createMockFabricCanvas>,
    options?: Partial<TikZExportOptions>
  ): Promise<string> {
    // Generate the code directly without going through blob
    const opts = { ...this.getDefaultOptions(), ...options };

    let tikzCode = '';

    if (opts.standalone) {
      tikzCode += '\\documentclass{standalone}\n';
      tikzCode += '\\usepackage{tikz}\n';
      tikzCode += '\\begin{document}\n';
    }

    if (opts.includePreamble && !opts.standalone) {
      tikzCode += '% Include in preamble: \\usepackage{tikz}\n';
    }

    tikzCode += '\\begin{tikzpicture}';
    if (opts.scale !== 1) {
      tikzCode += `[scale=${opts.scale}]`;
    }
    tikzCode += '\n';

    if (opts.includeComments) {
      tikzCode += '  % Generated by FINNISH Export Pipeline\n';
    }

    const objects = canvas.getObjects();
    for (const obj of objects) {
      tikzCode += this.objectToTikZ(obj, opts);
    }

    tikzCode += '\\end{tikzpicture}\n';

    if (opts.standalone) {
      tikzCode += '\\end{document}\n';
    }

    return tikzCode;
  }
}

interface TikZExportOptions {
  format: 'tikz';
  standalone?: boolean;
  includePreamble?: boolean;
  scale?: number;
  unit?: 'cm' | 'mm' | 'pt' | 'in';
  includeComments?: boolean;
  filename?: string;
}

// ============================================================================
// Test Helpers
// ============================================================================

/**
 * Create canvas with test objects
 */
const createCanvasWithObjects = () => {
  const canvas = createMockFabricCanvas();

  // Add test objects
  const objects = [
    {
      type: 'rect',
      id: 'rect-1',
      left: 50,
      top: 50,
      width: 100,
      height: 80,
      fill: '#3498db',
      stroke: '#2980b9',
    },
    {
      type: 'circle',
      id: 'circle-1',
      left: 200,
      top: 100,
      radius: 50,
      fill: '#e74c3c',
    },
    {
      type: 'text',
      id: 'text-1',
      left: 100,
      top: 200,
      text: 'Test Label',
      fontSize: 16,
      fontFamily: 'Arial',
      fill: '#2c3e50',
    },
  ];

  canvas._objects = objects;
  canvas.getObjects.mockReturnValue(objects);

  return canvas;
};

/**
 * Track progress updates
 */
const createProgressTracker = () => {
  const updates: { progress: number; message?: string }[] = [];
  const callback = (progress: number, message?: string) => {
    updates.push({ progress, message });
  };
  return { callback, updates };
};

// ============================================================================
// Integration Tests
// ============================================================================

describe('Export Pipeline Integration Tests', () => {
  let mockCanvas: ReturnType<typeof createMockFabricCanvas>;

  beforeEach(() => {
    mockCanvas = createCanvasWithObjects();
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // ==========================================================================
  // PNG Export Tests at Different DPIs
  // ==========================================================================

  describe('PNG Export at Different DPIs', () => {
    let pngExporter: PNGExporter;

    beforeEach(() => {
      pngExporter = new PNGExporter();
    });

    it('should export at 72 DPI (web quality)', async () => {
      const result = await pngExporter.export(mockCanvas as any, { dpi: 72 });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.mimeType).toBe('image/png');
      expect(result.filename).toBe('illustration.png');
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          format: 'png',
          multiplier: 1, // 72/72 = 1
        })
      );
    });

    it('should export at 150 DPI (default quality)', async () => {
      const result = await pngExporter.export(mockCanvas as any, { dpi: 150 });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          multiplier: expect.closeTo(150 / 72, 1),
        })
      );
    });

    it('should export at 300 DPI (print quality)', async () => {
      const result = await pngExporter.export(mockCanvas as any, { dpi: 300 });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          multiplier: expect.closeTo(300 / 72, 1),
        })
      );
    });

    it('should export at 600 DPI (high-res print quality)', async () => {
      const result = await pngExporter.export(mockCanvas as any, { dpi: 600 });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          multiplier: expect.closeTo(600 / 72, 1),
        })
      );
    });

    it('should reject invalid DPI values', () => {
      const validation = pngExporter.validateOptions({ dpi: 400 as DPI });

      expect(validation.valid).toBe(false);
      expect(validation.errors).toContain('DPI must be one of: 72, 150, 300, 600');
    });

    it('should use convenience method for print export', async () => {
      const result = await pngExporter.exportForPrint(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          multiplier: expect.closeTo(300 / 72, 1),
        })
      );
    });

    it('should use convenience method for web export', async () => {
      const result = await pngExporter.exportForWeb(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.toDataURL).toHaveBeenCalledWith(
        expect.objectContaining({
          multiplier: 1,
          quality: 0.85,
        })
      );
    });

    it('should handle transparent background', async () => {
      const result = await pngExporter.export(mockCanvas as any, { transparent: true });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(mockCanvas.backgroundColor).toBeDefined();
    });

    it('should report progress during export', async () => {
      const tracker = createProgressTracker();

      await pngExporter.export(mockCanvas as any, {}, tracker.callback);

      expect(tracker.updates.length).toBeGreaterThan(0);
      expect(tracker.updates[0].progress).toBe(0);
      expect(tracker.updates[tracker.updates.length - 1].progress).toBe(100);
    });

    it('should estimate file size for given options', () => {
      const estimate = pngExporter.estimateFileSize(mockCanvas as any, { dpi: 300 });

      expect(estimate.min).toBeGreaterThan(0);
      expect(estimate.max).toBeGreaterThan(estimate.min);
      expect(['KB', 'MB']).toContain(estimate.unit);
    });
  });

  // ==========================================================================
  // SVG Export with Optimization Tests
  // ==========================================================================

  describe('SVG Export with Optimization', () => {
    let svgExporter: SVGExporter;

    beforeEach(() => {
      svgExporter = new SVGExporter();
    });

    it('should export valid SVG', async () => {
      const result = await svgExporter.export(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.mimeType).toBe('image/svg+xml');
      expect(result.filename).toBe('illustration.svg');
    });

    it('should optimize SVG by removing comments', async () => {
      mockCanvas.toSVG.mockReturnValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><!-- This is a comment --><rect/></svg>'
      );

      const svgString = await svgExporter.exportAsString(mockCanvas as any, { optimize: true });

      expect(svgString).not.toContain('<!-- This is a comment -->');
    });

    it('should optimize SVG by removing empty groups', async () => {
      mockCanvas.toSVG.mockReturnValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><g></g><g><rect/></g></svg>'
      );

      const svgString = await svgExporter.exportAsString(mockCanvas as any, { optimize: true });

      expect(svgString).not.toContain('<g></g>');
      expect(svgString).toContain('<rect');
    });

    it('should remove data-* attributes when optimizing', async () => {
      mockCanvas.toSVG.mockReturnValue(
        '<svg xmlns="http://www.w3.org/2000/svg"><rect data-fabric-id="123" data-custom="value"/></svg>'
      );

      const svgString = await svgExporter.exportAsString(mockCanvas as any, { optimize: true });

      expect(svgString).not.toContain('data-fabric-id');
      expect(svgString).not.toContain('data-custom');
    });

    it('should preserve content when optimization is disabled', async () => {
      const originalSvg = '<svg xmlns="http://www.w3.org/2000/svg"><!-- comment --><g></g></svg>';
      mockCanvas.toSVG.mockReturnValue(originalSvg);

      const svgString = await svgExporter.exportAsString(mockCanvas as any, { optimize: false });

      expect(svgString).toContain('<!-- comment -->');
    });

    it('should minify SVG when option is enabled', async () => {
      mockCanvas.toSVG.mockReturnValue(
        '<svg xmlns="http://www.w3.org/2000/svg">\n  <rect/>\n  <circle/>\n</svg>'
      );

      const svgString = await svgExporter.exportAsString(mockCanvas as any, { minify: true });

      // Minified output should have no extra whitespace
      expect(svgString).not.toMatch(/\n\s+\n/);
    });

    it('should preserve viewBox when option is enabled', async () => {
      await svgExporter.export(mockCanvas as any, { preserveViewBox: true });

      expect(mockCanvas.toSVG).toHaveBeenCalledWith(
        expect.objectContaining({
          viewBox: expect.objectContaining({
            minX: 0,
            minY: 0,
          }),
        })
      );
    });

    it('should ensure xmlns is present', async () => {
      mockCanvas.toSVG.mockReturnValue('<svg><rect/></svg>');

      const svgString = await svgExporter.exportAsString(mockCanvas as any);

      expect(svgString).toContain('xmlns="http://www.w3.org/2000/svg"');
    });

    it('should add XML declaration', async () => {
      mockCanvas.toSVG.mockReturnValue('<svg xmlns="http://www.w3.org/2000/svg"></svg>');

      const svgString = await svgExporter.exportAsString(mockCanvas as any);

      expect(svgString).toMatch(/^<\?xml version="1\.0" encoding="UTF-8"\?>/);
    });

    it('should export as data URL', async () => {
      const dataURL = await svgExporter.exportAsDataURL(mockCanvas as any);

      expect(dataURL).toMatch(/^data:image\/svg\+xml,/);
    });

    it('should export as base64 data URL', async () => {
      const dataURL = await svgExporter.exportAsBase64DataURL(mockCanvas as any);

      expect(dataURL).toMatch(/^data:image\/svg\+xml;base64,/);

      // Verify base64 is valid
      const base64Part = dataURL.replace('data:image/svg+xml;base64,', '');
      expect(() => atob(base64Part)).not.toThrow();
    });

    it('should report progress during export', async () => {
      const tracker = createProgressTracker();

      await svgExporter.export(mockCanvas as any, {}, tracker.callback);

      expect(tracker.updates.length).toBeGreaterThan(0);
      expect(tracker.updates[tracker.updates.length - 1].progress).toBe(100);
    });
  });

  // ==========================================================================
  // PDF Generation Tests
  // ==========================================================================

  describe('PDF Generation', () => {
    let pdfExporter: PDFExporter;

    beforeEach(() => {
      pdfExporter = new PDFExporter();
    });

    it('should export valid PDF', async () => {
      const result = await pdfExporter.export(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.mimeType).toBe('application/pdf');
      expect(result.filename).toBe('illustration.pdf');
    });

    it('should use letter page size by default', async () => {
      const defaults = pdfExporter.getDefaultOptions();

      expect(defaults.pageSize).toBe('letter');
      expect(defaults.orientation).toBe('portrait');
    });

    it('should support A4 page size', async () => {
      const result = await pdfExporter.export(mockCanvas as any, { pageSize: 'a4' });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.size).toBeGreaterThan(0);
    });

    it('should support landscape orientation', async () => {
      const result = await pdfExporter.export(mockCanvas as any, { orientation: 'landscape' });

      expect(result.blob).toBeInstanceOf(Blob);
    });

    it('should support custom page dimensions', async () => {
      const validation = pdfExporter.validateOptions({
        pageSize: 'custom',
        customWidth: 500,
        customHeight: 400,
      });

      expect(validation.valid).toBe(true);
    });

    it('should reject custom size without dimensions', () => {
      const validation = pdfExporter.validateOptions({
        pageSize: 'custom',
        // Missing customWidth and customHeight
      });

      expect(validation.valid).toBe(false);
    });

    it('should set document metadata', async () => {
      const result = await pdfExporter.export(mockCanvas as any, {
        title: 'Test Document',
        author: 'Test Author',
        subject: 'Integration Test',
      });

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.size).toBeGreaterThan(0);
    });

    it('should apply margin setting', async () => {
      const validation = pdfExporter.validateOptions({ margin: 72 }); // 1 inch

      expect(validation.valid).toBe(true);
    });

    it('should reject negative margins', () => {
      const validation = pdfExporter.validateOptions({ margin: -10 });

      expect(validation.valid).toBe(false);
    });

    it('should export vector PDF', async () => {
      const result = await pdfExporter.exportAsVector(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.mimeType).toBe('application/pdf');
    });

    it('should report progress during export', async () => {
      const tracker = createProgressTracker();

      await pdfExporter.export(mockCanvas as any, {}, tracker.callback);

      expect(tracker.updates.length).toBeGreaterThan(0);
      expect(tracker.updates[tracker.updates.length - 1].progress).toBe(100);
    });

    it('should estimate page count', () => {
      const pageCount = pdfExporter.estimatePageCount(mockCanvas as any);

      expect(pageCount).toBe(1); // Currently single-page only
    });
  });

  // ==========================================================================
  // TikZ Code Generation Tests
  // ==========================================================================

  describe('TikZ Code Generation', () => {
    let tikzExporter: TikZExporter;

    beforeEach(() => {
      tikzExporter = new TikZExporter();
    });

    it('should export valid TikZ code', async () => {
      const result = await tikzExporter.export(mockCanvas as any);

      expect(result.blob).toBeInstanceOf(Blob);
      expect(result.mimeType).toBe('text/x-tex');
      expect(result.filename).toBe('illustration.tex');
    });

    it('should generate tikzpicture environment', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any);

      expect(tikzCode).toContain('\\begin{tikzpicture}');
      expect(tikzCode).toContain('\\end{tikzpicture}');
    });

    it('should generate standalone document when option is enabled', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { standalone: true });

      expect(tikzCode).toContain('\\documentclass{standalone}');
      expect(tikzCode).toContain('\\usepackage{tikz}');
      expect(tikzCode).toContain('\\begin{document}');
      expect(tikzCode).toContain('\\end{document}');
    });

    it('should include preamble comment when not standalone', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, {
        standalone: false,
        includePreamble: true,
      });

      expect(tikzCode).toContain('% Include in preamble');
      expect(tikzCode).toContain('\\usepackage{tikz}');
    });

    it('should apply scale factor', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { scale: 0.5 });

      expect(tikzCode).toContain('[scale=0.5]');
    });

    it('should use specified unit', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { unit: 'mm' });

      expect(tikzCode).toContain('mm');
    });

    it('should include comments when enabled', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { includeComments: true });

      expect(tikzCode).toContain('% Generated by FINNISH');
    });

    it('should exclude comments when disabled', async () => {
      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { includeComments: false });

      expect(tikzCode).not.toContain('% Rectangle');
      expect(tikzCode).not.toContain('% Circle');
    });

    it('should convert rectangles to TikZ', async () => {
      mockCanvas._objects = [
        { type: 'rect', left: 100, top: 100, width: 200, height: 150, fill: '#ff0000' },
      ];
      mockCanvas.getObjects.mockReturnValue(mockCanvas._objects);

      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any);

      expect(tikzCode).toContain('\\filldraw');
      expect(tikzCode).toContain('rectangle');
    });

    it('should convert circles to TikZ', async () => {
      mockCanvas._objects = [
        { type: 'circle', left: 200, top: 200, radius: 50 },
      ];
      mockCanvas.getObjects.mockReturnValue(mockCanvas._objects);

      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any);

      expect(tikzCode).toContain('\\draw');
      expect(tikzCode).toContain('circle');
    });

    it('should handle unsupported object types gracefully', async () => {
      mockCanvas._objects = [
        { type: 'unsupported-type', left: 100, top: 100 },
      ];
      mockCanvas.getObjects.mockReturnValue(mockCanvas._objects);

      const tikzCode = await tikzExporter.exportAsString(mockCanvas as any, { includeComments: true });

      expect(tikzCode).toContain('% Unsupported object type: unsupported-type');
    });

    it('should reject invalid scale values', () => {
      const validation = tikzExporter.validateOptions({ scale: -1 });

      expect(validation.valid).toBe(false);
      expect(validation.errors).toContain('Scale must be positive');
    });

    it('should reject invalid unit values', () => {
      const validation = tikzExporter.validateOptions({ unit: 'invalid' as any });

      expect(validation.valid).toBe(false);
      expect(validation.errors).toContain('Invalid unit');
    });

    it('should report progress during export', async () => {
      const tracker = createProgressTracker();

      await tikzExporter.export(mockCanvas as any, {}, tracker.callback);

      expect(tracker.updates.length).toBeGreaterThan(0);
      expect(tracker.updates[tracker.updates.length - 1].progress).toBe(100);
    });
  });

  // ==========================================================================
  // Cross-Format Consistency Tests
  // ==========================================================================

  describe('Cross-Format Consistency', () => {
    it('should use consistent default filenames across formats', () => {
      const pngDefaults = new PNGExporter().getDefaultOptions();
      const svgDefaults = new SVGExporter().getDefaultOptions();
      const pdfDefaults = new PDFExporter().getDefaultOptions();
      const tikzDefaults = new TikZExporter().getDefaultOptions();

      expect(pngDefaults.filename).toBe('illustration');
      expect(svgDefaults.filename).toBe('illustration');
      expect(pdfDefaults.filename).toBe('illustration');
      expect(tikzDefaults.filename).toBe('illustration');
    });

    it('should use correct file extensions for each format', async () => {
      const pngResult = await new PNGExporter().export(mockCanvas as any);
      const svgResult = await new SVGExporter().export(mockCanvas as any);
      const pdfResult = await new PDFExporter().export(mockCanvas as any);
      const tikzResult = await new TikZExporter().export(mockCanvas as any);

      expect(pngResult.filename).toMatch(/\.png$/);
      expect(svgResult.filename).toMatch(/\.svg$/);
      expect(pdfResult.filename).toMatch(/\.pdf$/);
      expect(tikzResult.filename).toMatch(/\.tex$/);
    });

    it('should use correct MIME types for each format', async () => {
      const pngResult = await new PNGExporter().export(mockCanvas as any);
      const svgResult = await new SVGExporter().export(mockCanvas as any);
      const pdfResult = await new PDFExporter().export(mockCanvas as any);
      const tikzResult = await new TikZExporter().export(mockCanvas as any);

      expect(pngResult.mimeType).toBe('image/png');
      expect(svgResult.mimeType).toBe('image/svg+xml');
      expect(pdfResult.mimeType).toBe('application/pdf');
      expect(tikzResult.mimeType).toBe('text/x-tex');
    });

    it('should all have format property defined', () => {
      expect(new PNGExporter().format).toBe('png');
      expect(new SVGExporter().format).toBe('svg');
      expect(new PDFExporter().format).toBe('pdf');
      expect(new TikZExporter().format).toBe('tikz');
    });

    it('should all support custom filenames', async () => {
      const customFilename = 'my-custom-diagram';

      const pngResult = await new PNGExporter().export(mockCanvas as any, { filename: customFilename });
      const svgResult = await new SVGExporter().export(mockCanvas as any, { filename: customFilename });
      const pdfResult = await new PDFExporter().export(mockCanvas as any, { filename: customFilename });
      const tikzResult = await new TikZExporter().export(mockCanvas as any, { filename: customFilename });

      expect(pngResult.filename).toBe(`${customFilename}.png`);
      expect(svgResult.filename).toBe(`${customFilename}.svg`);
      expect(pdfResult.filename).toBe(`${customFilename}.pdf`);
      expect(tikzResult.filename).toBe(`${customFilename}.tex`);
    });

    it('should all report size in bytes', async () => {
      const pngResult = await new PNGExporter().export(mockCanvas as any);
      const svgResult = await new SVGExporter().export(mockCanvas as any);
      const pdfResult = await new PDFExporter().export(mockCanvas as any);
      const tikzResult = await new TikZExporter().export(mockCanvas as any);

      expect(pngResult.size).toBeGreaterThan(0);
      expect(svgResult.size).toBeGreaterThan(0);
      expect(pdfResult.size).toBeGreaterThan(0);
      expect(tikzResult.size).toBeGreaterThan(0);
    });
  });

  // ==========================================================================
  // Error Handling Tests
  // ==========================================================================

  describe('Error Handling', () => {
    it('should handle canvas export errors gracefully', async () => {
      const errorCanvas = createMockFabricCanvas();
      errorCanvas.toDataURL.mockImplementation(() => {
        throw new Error('Canvas export failed');
      });

      const pngExporter = new PNGExporter();

      await expect(pngExporter.export(errorCanvas as any)).rejects.toThrow('Canvas export failed');
    });

    it('should handle SVG generation errors', async () => {
      const errorCanvas = createMockFabricCanvas();
      errorCanvas.toSVG.mockImplementation(() => {
        throw new Error('SVG generation failed');
      });

      const svgExporter = new SVGExporter();

      await expect(svgExporter.export(errorCanvas as any)).rejects.toThrow('SVG generation failed');
    });

    it('should validate options before export', async () => {
      const pngExporter = new PNGExporter();

      await expect(
        pngExporter.export(mockCanvas as any, { quality: 150 })
      ).rejects.toThrow('Invalid export options');
    });
  });
});
